<a href="https://colab.research.google.com/github/Wisawasi/data-science-ipython-notebooks/blob/master/146_tutorial_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img height="45px" src="https://avatars3.githubusercontent.com/u/20337240?s=460&v=4" align="left" hspace="10px" vspace="0px">

# การใช้งานโมดูล numpy เบื้องต้น

เอาไว้ใช้งานชนิดข้อมูลแบบอาร์เรย์หลายมิติ (ndarray)


<hr>
<a href='https://www.facebook.com/programmerthai'><font color='green'>สรุปและเรียบเรียงโดย โปรแกรมเมอร์ไทย thai programmer</font></a>

cite

https://colab.research.google.com/drive/1NQDtO3Y8kApxS5SwMPE2hvdUl3T_of4V

# วิธีใช้งาน colab

Colab พัฒนาโดย google เป็นหน้าเว็บเอาไว้ใช้เขียนโค้ด python ได้ผ่านทางหน้าเว็บ และเชื่อมต่อกับ google drive ของเราก็ได้ด้วย ซึ่ง colab หน้านี้**ได้รวบรวมเนื้อหา Python ของม.ต้น** เอาไว้ แต่ก่อนอื่นอยากให้ดูวิธีการใช้งาน colab เสียก่อน

<font color='red'>** ต้องมี Gmail และ google drive</font>

<hr/>

<h3>วิธี 1) กด "Open in playgrouhd"</h3>
<div>
<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2020/05/python_matayom_4.png" align="center" hspace="10px" vspace="0px">


<hr/>

<h3>วิธี 2) กด Save a copy in Drive ... เพื่อบันทึกไว้ google drive เครื่องเรา</h3>

<img height="300px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_1.png" align="center" hspace="10px" vspace="0px">

<br/>

<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_2.png" align="center" hspace="10px" vspace="0px">

<hr/>

<h3>จากนั้นถึงจะสามารถรันได้</h3>
<img height="200px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/11/python_matayom_3.png" align="center" hspace="10px" vspace="0px">

# Import package

In [ ]:
import numpy as np

# สร้าง ndarray

**สร้างจาก List**

In [ ]:
# list ปกติ
[10, 20, 30, 40, 50]


[10, 20, 30, 40, 50]

In [ ]:
# ndarray
np.array([10, 20, 30, 40, 50])

array([10, 20, 30, 40, 50])

In [ ]:
type( np.array([10, 20, 30, 40, 50]) )


numpy.ndarray

In [ ]:
np.array([10, 20, 30, 40, 50]).shape

(5,)

**สร้างจาก List หลายมิติ**

In [ ]:
# List ปกติ
[[10, 20, 30], [10, 20 ,30]]

[[10, 20, 30], [10, 20, 30]]

In [ ]:
np.array([[10, 20, 30], [40, 50 ,60]])

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
np.array([[10, 20, 30], [40, 50 ,60]]).shape

(2, 3)

In [ ]:
x = np.array([[10, 20, 30], [40, 50 ,60], [70, 80, 90]])
print(x)
print(x.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


**สร้างจากฟังก์ชัน**

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full( (4,5), 3.2)

array([[3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2, 3.2]])

**สร้างสมาชิกแบบเพิมขึ้นแบบ range**

In [ ]:
np.arange(5) # เริ่มตั้งแต่ 0 แต่ยังไม่ถึง 5 (เพิ่มทีละ 1 ค่า)

array([0, 1, 2, 3, 4])

In [ ]:
# เริ่มที่ 0 ไปที่ละ 2 ค่า แต่ยังไม่ถึง 10
np.arange(0, 10, 2) # default เพิ่มที่ละหนึ่ง

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(5, 10) # เพิ่มทีละหนึ่ง (default) เริ่มตั้งแต่เลข 5 แต่ยังไม่ถึง 10

array([5, 6, 7, 8, 9])

In [ ]:
# สร้างเลขระหว่าง 0 ถึง 1 โดยจะมี 4 ค่า
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

**หรือจะสร้างแบบลดลงก็ได้**

In [ ]:
np.arange(10, 0, -1) # เริ่มจาก 10 ลดไปทีละ -1 แต่ยังไม่ถึง 0

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

**สร้างสมาชิกแบบ random**

In [ ]:
mean = 10
stdev = 3
number_values = 20
np.random.normal(mean, stdev, number_values)

array([14.01446465, 11.31696399,  3.68314176, 15.45088067, 10.73019054,
        9.91463996,  5.74890406,  6.18349831,  5.84764651, 15.00389177,
        3.72220097,  4.25767887,  2.81945448,  9.18999147, 11.79956519,
        5.63827975,  9.04887865,  9.96530223,  9.57361103,  8.998003  ])

In [ ]:
np.random.randint(0, 10, 6)  # สุ่มค่าตั้งแต่ 0 ถึง 10 มีจำนวนสมาชิก 6 ตัว

array([9, 5, 9, 5, 3, 5])

# Reshape

In [ ]:
x = np.arange(6)
print(x)
print("after reshape")
x.reshape(2, 3)

[0 1 2 3 4 5]
after reshape


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x = np.array([[10, 20, 30], [40, 50 ,60]])
print(x)
print("after reshape")
x.reshape(3, 2)

[[10 20 30]
 [40 50 60]]
after reshape


array([[10, 20],
       [30, 40],
       [50, 60]])

In [ ]:
x = np.array([[10, 20] , [30, 40] , [50 ,60], [70, 80]])
print(x)
print("after reshape")
x.reshape(2,4)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
after reshape


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# เข้าถึง index

In [ ]:
x = np.arange(5)

print(x)
print(x[4])

# อินเดกซ์เป็นลบ
print(x[-1])

[0 1 2 3 4]
4
4


Slice

In [ ]:
x = np.arange(5)

print(x[1:3])
print(x[1:])
print(x[:3])

# อินเดกซ์เป็นลบ
print('Index is negative')
print(x[-4:-2])
print(x[-4:])
print(x[:-2])


[1 2]
[1 2 3 4]
[0 1 2]
Index is negative
[1 2]
[1 2 3 4]
[0 1 2]


เพิ่มทีละสเตป

In [ ]:
print(x)
x[::2] # slice มาห่างกันทีละ 2 อินเด็กซ์

[0 1 2 3 4]


array([0, 2, 4])

In [ ]:
print(x)
x[0:3:2] # slice เริ่มต้นที่อินเด็กซ์ 0 ยังไม่ถึง 3 แต่เพิ่มทีละ 2 อินเด็กซ์

[0 1 2 3 4]


array([0, 2])

สามารถมีสเตป เป็นลบได้ ประยุกต์ revese ย้อนกลับหลังได้

In [ ]:
x[::-1] # ขยับลดทีละ -1 อินเด็กซ์ จากหลังไปหน้า

array([4, 3, 2, 1, 0])

In [ ]:
x[::-2] # ขยับลดทีละ -2 อินเด็กซ์ จากหลังไปหน้า

array([4, 2, 0])

In [ ]:
x[4:2:-1] # ตำแหน่งเริ่มต้นอินเด็กซ์ 4 ไล่ย้อนมายังไม่ถึงอินเดกซ์ 2 โดยลดทีละ -1

array([4, 3])

ใช้ : หมายถึงเข้าถึงทั้งหมดในมิตินั้น

In [ ]:
x[:]

[0 1 2 3 4]


แก้ไขข้อมูลทั้งชุด

In [ ]:
x[:] = 255 # ห้ามเขียน x = 255
x 

array([255, 255, 255, 255, 255])

หรือจะแก้ไขบางช่วง

In [ ]:
x[2:4] = -100
x

array([ 255,  255, -100, -100,  255])

# เข้าถึงแอร์เรย์หลายมิติ

สร้างจากลิสต์

In [ ]:
# 2 มิติ
x1 = np.array([[10, 20, 30], [40, 50 ,60], [70, 80, 90]])
print("shape =", x1.shape)
print(x1)

# 3 มิติ
x2 = np.array( [ 
                [[1, 2, 3], 
                 [4, 5 ,6], 
                 [7, 8, 9]],               
                [[11, 12, 13], 
                 [14, 15 ,16], 
                 [17, 18, 19]]
              ]
             )

print("shape = ", x2.shape)
x2

shape = (3, 3)
[[10 20 30]
 [40 50 60]
 [70 80 90]]
shape =  (2, 3, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

สร้างกี่มิติก็ได้

In [ ]:
# สร้าง 4 มิติ
x = np.ones( (2 , 3 , 4, 5))
print("shape =", x.shape)
x

shape = (2, 3, 4, 5)


array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [ ]:
x = np.array([[10, 20, 30], [40, 50 ,60], [70, 80, 90]])

# เข้าถึงเฉพาะแถวที่ 2 (อินเดกซ์เป็น 1)
print(x[1])
print(x[-1])

[40 50 60]
[70 80 90]


เข้าถึงทีละตัวในอาร์เรย์หลายมิติ

In [ ]:
print(x)

print(x[2][2])
#หรือจะเขียน
print(x[2,2])
# เข้าถึงอินเด็กซ์เป็นลบ
print(x[-1][-1])
print(x[-1, -1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
90
90
90
90


เข้าถึงอาร์เรยหลายมิติแบบ slice

In [ ]:
print(x)
print(x[0:2, 0:2])

# เข้าถึงแบบอินเด็กซ์เป็นลบ
print(x[-2:, -2:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20]
 [40 50]]
[[50 60]
 [80 90]]


หรือจะ slice ระบุสเตป

In [ ]:
print(x)
print(x[::2, ::2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 30]
 [70 90]]


หรือจะเข้าถึงแบบลิสต์

In [ ]:
print(x)
x[:2][0:3]

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[10, 20, 30],
       [40, 50, 60]])

ใช้ : เพื่อเข้าถึงทั้งมิติ

In [ ]:
x = np.array( [ 
                [[1, 2, 3], 
                 [4, 5 ,6], 
                 [7, 8, 9]],
               
                [[11, 12, 13], 
                 [14, 15 ,16], 
                 [17, 18, 19]]
              ]
             )

print("shape = ", x.shape)
print( x[1, : , :])
print( x[:, 2 , :])
print( x[:, : , 0])

shape =  (2, 3, 3)
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 7  8  9]
 [17 18 19]]
[[ 1  4  7]
 [11 14 17]]


แก้ไขค่าทีเดียวได้

In [ ]:
x[0:1, : , :] = 72
x

array([[[ 72,  72,  72],
        [ 72,  72,  72],
        [ 72,  72,  72]],

       [[255, 255, 255],
        [ 14,  15,  16],
        [ 17,  18,  19]]])

In [ ]:
x[:, 0:1 , :] = 255
x

array([[[255, 255, 255],
        [ 72,  72,  72],
        [ 72,  72,  72]],

       [[255, 255, 255],
        [ 14,  15,  16],
        [ 17,  18,  19]]])

In [ ]:
x [:, :, 1:3] = -10
x

array([[[255, -10, -10],
        [ 72, -10, -10],
        [ 72, -10, -10]],

       [[255, -10, -10],
        [ 14, -10, -10],
        [ 17, -10, -10]]])

หรือจะเปลี่ยนทุกค่าในที่เดียวจบ

In [ ]:
x[:, :, :] = -333 # ห้ามเขียน x
x

array([[[-333, -333, -333],
        [-333, -333, -333],
        [-333, -333, -333]],

       [[-333, -333, -333],
        [-333, -333, -333],
        [-333, -333, -333]]])

# เข้าถึงด้วยการระบุ index ไม่มีช่วง

In [ ]:
indices = [0, 4, 5] # ใช้ List ระบุอินเดกซ์ที่ต้องการเลืก
x = np.array([0, 10 , 20 , 30 , 40 , 50, 60, 70 ,80, 90])
print(x)
print(x[indices])

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 40 50]


ไม่ต้องเรียงลำดับก็ได้ 

In [ ]:
indices = [0, 7, 5, 2]
x = np.array([0, 10 , 20 , 30 , 40 , 50, 60, 70 ,80, 90])
print(x)
print(x[indices])
# เสมือนเขียน print(x[[0, 7, 5, 2]])

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 70 50 20]


นำไปประยุกต์จัดเรียงตำแหน่งใหม่

In [ ]:
x = np.array([0, 10, 20, 30, 40])
print(x)
x[ [1, 4, 3, 0, 2]]

[ 0 10 20 30 40]


array([10, 40, 30,  0, 20])

ระบุอินเด็กซ์ติดลบก็ได้ด้วย

In [ ]:
indices = [0, -2, -1]
x = np.array([0, 10, 20, 30, 40])
print(x)
print(x[indices])

[ 0 10 20 30 40]
[ 0 30 40]


ระบุอินเด็กซ์โดยใช้ ndarray ก็ได้

In [ ]:
indices = np.array([0, 7, 5, 2])
x = np.arange(10)
print(x)
print(x[indices])

[0 1 2 3 4 5 6 7 8 9]
[0 7 5 2]


ระบุเป็น Boolean ก็ได้

In [ ]:
x = np.arange(5)
print(x)
print(x[[True, False, False, True, True]]) # เลือกสามาชิกที่ตำแหน่งตรง True

[0 1 2 3 4]
[0 3 4]


หาอินเด็กซ์ที่ต้องการ

In [ ]:
x = np.array([0, 10, 20 ,30 ,40 ,50, 60, 70 ,80, 90])
print(x)
np.where(x>50)

[ 0 10 20 30 40 50 60 70 80 90]


(array([6, 7, 8, 9]),)

In [ ]:
indices = np.random.permutation(20) # แรนดอม อินเดกซ์
indices

array([11,  0,  9,  2,  1, 10,  8,  4, 18, 13, 14,  6,  7, 19, 12, 17, 15,
        5, 16,  3])

# เปรียบเทียบ

In [ ]:
x = np.arange(10)
print(x > 5) # นำสมาชิกทุกตัวมาเปรียบเทียบ ได้เป็นอาร์เรย์ของ boolean
print(x !=7) # นำสมาชิกทุกตัวมาเปรียบเทียบ ได้เป็นอาร์เรย์ของ boolean

[False False False False False False  True  True  True  True]
[ True  True  True  True  True  True  True False  True  True]


In [ ]:
x = np.arange(10)
(x>5) & (x !=7)

array([False, False, False, False, False, False,  True, False,  True,
        True])

ประยุกต์เลือกสมาชิกในอาร์เรย์

In [ ]:
x = np.arange(10)
print(x)
print(x>5)
x[x>5]

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]


array([6, 7, 8, 9])

In [ ]:
x = np.arange(10)
print(x)
print((x>5) & (x!=7))
x[(x>5) & (x!=7)]

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True False  True  True]


array([6, 8, 9])

# ดำเนินการทางคณิตศาสตร์

อาร์เรย์ กับ scalar

In [ ]:
x = np.arange(5)
print(x)
-10*x


[0 1 2 3 4]


array([  0, -10, -20, -30, -40])

In [ ]:
x = np.array([2, 3, 5, 7, 9])
print(x)
x + 10

[2 3 5 7 9]


array([12, 13, 15, 17, 19])

อาร์เรย์ กับ อาร์เรย์

In [ ]:
a = np.arange(5)
b = np.arange(5,10)
print(a)
print(b)
a + b

[0 1 2 3 4]
[5 6 7 8 9]


array([ 5,  7,  9, 11, 13])

In [ ]:
a = np.arange(5)
b = np.arange(5,10)

a**2 / b*10

array([ 0.        ,  1.66666667,  5.71428571, 11.25      , 17.77777778])

สามารถกระทำหลายมิติก็ได้ด้วย

In [ ]:
a = np.ones( (2,3) )
b = np.full( (2,3), 10)

print(a)
print(b)
a/4 + 3* b

[[1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10]
 [10 10 10]]


array([[30.25, 30.25, 30.25],
       [30.25, 30.25, 30.25]])

# ตัวอย่างเมธอด

In [ ]:
x = np.array([[10, 20] , [30, 40] , [50 ,60], [70, 80]])
print(x)

x.min()

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


10

In [ ]:
x.max()

80

In [ ]:
x.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 360])

In [ ]:
x.cumprod()

array([           10,           200,          6000,        240000,
            12000000,     720000000,   50400000000, 4032000000000])

# มีฟังก์ชันใช้งานกับ list ได้

In [ ]:
x = [[10, 20] , [30, 40] , [50 ,60], [70, 80]]
np.shape(x)

(4, 2)

In [ ]:
np.min(x)

10

In [ ]:
np.max(x)

80

In [ ]:
np.cumsum(x)

array([ 10,  30,  60, 100, 150, 210, 280, 360])

In [ ]:
np.cumprod(x)

array([           10,           200,          6000,        240000,
            12000000,     720000000,   50400000000, 4032000000000])

# ฝากติดตาม

<img height="20px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2017/06/logo_facebook2.png" align="left" hspace="10px" vspace="0px">  https://www.facebook.com/programmerthai/

<img height="14px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/03/youtube.png" align="left" hspace="10px" vspace="3px">  https://www.youtube.com/channel/UCvhCKtG5cRE6K5--RJPql_w

<img height="14px" src="https://www.patanasongsivilai.com/blog/wp-content/uploads/2019/09/github-2.jpg" align="left" hspace="10px" vspace="3px">https://github.com/adminho/machine-learning

In [ ]:
#@title ฝากประชาสัมพันธ์ หนังสือ AI (ปัญญาประดิษฐ์) ไม่ยาก เรียนรู้ได้ด้วยเลขม. ปลาย ราคา 295 บาท
%%HTML
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fprogrammerthai%2Fphotos%2Fa.2410667485889755%2F2555677101388792%2F%3Ftype%3D3&width=500" width="500" height="588" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>